language: python
sudo: false
branches:
  only:
  - master
python:
- '3.6'
install:
- echo "Testing echo install"
- pip install --upgrade setuptools
- pip install -r requirements.txt
script:
- echo "script section"
- py.test adam_home/adam/ --cov=adam --ignore=adam/tests/integration_tests/hypercube_test.py
