language: python
sudo: false
branches:
  only:
  - master
python:
- '3.6'
install:
- pip install --upgrade setuptools
- pip install -r requirements.txt
before_script: cd adam_home
script:
- py.test adam --cov=adam --ignore=adam_home/adam/tests/integration_tests/hypercube_test.py
after_success:
- coveralls
before_install:
- openssl aes-256-cbc -in test_config.json.enc -out test_config.json -K 000000000000000000000000000000000000 -iv 000000000000000000000000000000000000 -d -p
