language: python
sudo: false
branches:
  only:
  - master
python:
- '3.6'
install:
- pip install --upgrade setuptools
- pip install -r requirements.txt
before_script: cd adam_home
flake8 .
script:
- py.test tests
after_success:
- coveralls
