language: python
sudo: false
branches:
  only:
  - master
python:
- '3.6'
install:
- pip install --upgrade setuptools
- pip install -r requirements.txt
before_script:
- cd adam_home 
- flake8 --max-line-length=125 --ignore=F401,F403 . 
script:
- py.test tests
#before_install:
#- openssl aes-256-cbc -K $encrypted_d1491136c3fb_key -iv $encrypted_d1491136c3fb_iv
#  -in test_config.json.enc -out test_config.json -d
